<?php
$title = 'Editar Usuário';
$xopencrypt = new \Xoperator\Xcore\XopEncrypt();
$this->headTitle($title);
?>
<script type="text/javascript">
//        $(document).ready(function() {
//                $('#password-form').prepend(
//                    '<a id="print" href="#"><img align="absmiddle" src="../../images/botao_imprimir.jpg"\/><\/a>'
//                );
//        });
</script>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->texto;?>

<div class="row">
      <div class="col-md-8">
        <?php
        $form = $this->form;
        $form->setAttribute('action',
                $this->url('users', array('action' => 'edit', 'id'=>$this->id)));
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('id'));
        ?>
        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('username'))?></div>
        </div>
        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('email'))?></div>
        </div>
        <div class="form-group">
            <div class="col-sm-10" id="password-form" style="background:#ffff99;"><?=$this->formRow($form->get('password'))?></div>
        </div>
         
        <?php
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
        ?>
        <div class="form-group" style="margin-top: 20px;">
            <span class="btn btn-default">ID Usuário&nbsp;<?=$this->id?></span>
        </div>
      </div>
</div>