 <?php
 $title = 'Escolha menu';
 $this->headTitle($title);
 
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <div class="row">
      <div class="col-md-8">
          <?php echo $this->param?>
        <form class="form-horizontal" method="get">
            <div class="form-group">
                <select name="link-menu" class="form-control">
                    <option>Selecione</option>
                    <?php
                        foreach($this->menus as $menu):
                            echo '<option value="'.$menu->id.'">'.$menu->menu.'</option>'.PHP_EOL;
                        endforeach;
                    ?>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" name="new-link-menu" class="btn btn-info" value="Seguinte"/>
            </div>
        </form>
      </div>
 </div>