<?php
$title = 'Novo Menus';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->texto;?>
<div class="row">
      <?php echo $this->flashMessenger()->render();?>
      <div class="col-md-8">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('menus', array('action' => 'add')));
        $form->prepare();

        echo $this->form()->openTag($form);
        ?>

        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('menu'))?></div>
        </div>
        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('description'))?></div>
        </div>
         
        <?php
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
        ?>
      </div>
</div>