<?php
 foreach($this->menu_selected as $menu_sel):
     $menu_id = $menu_sel->id;
     $menu_menu = $menu_sel->menu;
     $menu_description = $menu_sel->description;
 endforeach;
 $title = 'Editar Link para Menu';
 $this->headTitle($title);
 
 ?>
 <h1><?php echo $this->escapeHtml($title); ?> "<?=$menu_menu?>"</h1>
 <div class="row">
      <p>About: <?=$menu_description?></p>
      <?php echo $this->flashMessenger()->render();?>
      <div class="col-md-8">
        <?php
        $form = $this->form;
        $form->setAttribute('action',
                $this->url('menus', array('action' => 'editLink', 'id'=>$this->id)));
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('id'));
        ?>

        echo $this->form()->openTag($form);
        ?>
        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('id_menu'))?></div>
        </div>
        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('value'))?></div>
        </div>
        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('link'))?></div>
        </div>
        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('description'))?></div>
        </div>
         
        <?php
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
        ?>
      </div>
 </div>