 <?php
 // module/Album/view/album/album/index.phtml:
 $title = 'Menus';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a class="btn btn-success" href="<?php echo $this->url('menus', array('action'=>'add'));?>">
         <span class="glyphicon glyphicon-plus"></span>&nbsp;
         <?php echo $this->translate('Adicionar novo menu')?>
     </a>
     <a class="btn btn-success" href="<?php echo $this->url('menus', array('action'=>'addLinkMenu'));?>">
         <span class="glyphicon glyphicon-plus"></span>&nbsp;
         <?php echo $this->translate('Adicionar links para menu')?>
     </a>
 </p>

 <table class="table">
 <tr>
     <th><?php echo $this->translate('Menu')?></th>
     <th><?php echo $this->translate('Descrição')?></th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($menus as $menu) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($menu->menu);?></td>
     <td><?php echo $this->escapeHtml($menu->description);?></td>
     <td>
         <span class="glyphicon glyphicon-pencil"></span>
         <a href="<?php echo $this->url('menus',
             array('action'=>'edit', 'id' => $menu->id));?>">Edit</a>
         &nbsp;
         <span class="glyphicon glyphicon-trash"></span>
         <a href="<?php echo $this->url('menus',
             array('action'=>'delete', 'id' => $menu->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
