<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Xoperator\Module'                 => __DIR__ . '/Module.php',
    'Xoperator\Config'                 => __DIR__ . '/config/module.config.php',
    'Xoperator\XoperatorConfig'        => __DIR__ . '/config/settings/xoperator.config.php',
);
