<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Login Xoperator'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . __xopPUBLIC__ .'/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . __xopPUBLIC__ .'/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . __xopPUBLIC__ . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . __xopPUBLIC__ . '/css/style.css')?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . __xopPUBLIC__ . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . __xopPUBLIC__ . '/js/jquery.min.js')
            ->prependFile($this->basePath() . __xopPUBLIC__ . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . __xopPUBLIC__ . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="container">
            <div class="row">
                <div style="background: #eeeeee; padding: 8px 10px;">
                    <h3><span class="glyphicon glyphicon-lock"></span>&nbsp;<?=__siteNAME__?></h3>
                    <?=$this->message_login?>
                    
                    <?php
                    $form = $this->form;
                    $form->setAttribute('action', $this->url('login'));
                    $form->prepare();

                    echo $this->form()->openTag($form);
                    ?>

                    <div class="form-group">
                        <div class="col-sm-10"><?= $this->formRow($form->get('email')) ?></div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-10"><?= $this->formRow($form->get('password')) ?></div>
                    </div>

                    <?php
                    echo $this->formSubmit($form->get('submit'));
                    echo $this->form()->closeTag();
                    ?>
                </div>
                <div style="margin-top: 15px;">

                        <span>&copy; <?php echo date('Y') ?> <?=__siteNAME__?>.</span>
                        <a title="Home"  href="<?= $this->escapeHtml(__siteHOST__) ?>">
                            <span class="glyphicon glyphicon-home"></span>&nbsp;Home</a>&nbsp;&nbsp;
                        <a title="E-mail administrador"  href="<?= $this->escapeHtml(__siteHOSTMAIL__) ?>">
                            <span class="glyphicon glyphicon-envelope"></span>&nbsp;Webmail</a>
                </div>
            </div>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>