<?php
$title = 'Novo Artigo';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->texto;?>
<div class="row">
      <div class="col-md-8">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('articles', array('action' => 'add')));
        $form->prepare();

        echo $this->form()->openTag($form);
        ?>
        
        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('url'))?></div>
        </div>          
        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('title'))?></div>
        </div>
        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('text'))?></div>
        </div>        
        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('id_image'))?></div>
        </div>
          <span>Os campos seguintes são importantes para buscadores como Google, Yahoo!, etc.</span>
        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('description'))?></div>
        </div>        
        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('tags'))?></div>
        </div>
         
        <?php
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
        ?>
      </div>
</div>