<?php
$title = 'Editar Artigo';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->texto;?>

<div class="row">
      <div class="col-md-8">
        <?php
        $form = $this->form;
        $form->setAttribute('action',
                $this->url('articles', array('action' => 'edit', 'id'=>$this->id)));
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('id'));
        ?>

        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('url'))?></div>
        </div>          
        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('title'))?></div>
        </div>
        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('text'))?></div>
        </div>        
        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('id_image'))?></div>
        </div>          
        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('description'))?></div>
        </div>        
        <div class="form-group">
            <div class="col-sm-10"><?=$this->formRow($form->get('tags'))?></div>
        </div>
          
        <?php
        echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
        ?>
        <div class="form-group" style="margin-top: 20px;">
            <span class="btn btn-default">ID Artigo&nbsp;<?=$this->id?></span>
        </div>
      </div>
</div>