 <?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Meus artigos';
 $this->headTitle($title);
 $cropLink = new \Xoperator\Xcore\OptionTags();
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a class="btn btn-success" href="<?php echo $this->url('articles', array('action'=>'add'));?>">
         <span class="glyphicon glyphicon-plus"></span>&nbsp;
         <?php echo $this->translate('Adicionar novo artigo')?>
     </a>
 </p>

 <table class="table">
 <tr>
     <th><?php echo $this->translate('Título')?></th>
     <th><?php echo $this->translate('Texto')?></th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($articles as $article) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($article->title);?></td>
     <td><?php echo  $cropLink->cropLink(substr($this->escapeHtml($article->text),0,150));?>...</td>
     <td>
         <span class="glyphicon glyphicon-pencil"></span>
         <a href="<?php echo $this->url('articles',
             array('action'=>'edit', 'id' => $article->id));?>">Edit</a>
         &nbsp;
         <span class="glyphicon glyphicon-trash"></span>
         <a href="<?php echo $this->url('articles',
             array('action'=>'delete', 'id' => $article->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
